apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb-primary:5432
    database: opcua
    user: opcua_admin
    secureJsonData:
      password: changeme_strong_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    jsonData:
      timeInterval: "15s"

  - name: Loki
    type: loki
    url: http://loki:3100
    jsonData:
      maxLines: 1000
